version: '3.7'
services:
  app:
    image: jqrdan/datastream-app:1.0.0
    ports:
      - "3000:3000"
    networks:
      - datastream_network
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    hostname: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms8192m -Xmx8192m"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - datastream_network
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms8192m -Xmx8192m"
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - datastream_network
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms8192m -Xmx8192m"
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - datastream_network
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    networks:
      - datastream_network
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - datastream_network
  kafka1:
    image: jqrdan/datastream-kafka:1.0.0
    ports:
      - "9092:9092"
      - "8777:8778"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_JOLOKIA_PORT: 8778
    depends_on:
      - zookeeper
    volumes:
      - kafka01:/var/lib/kafka/data
    deploy:
      restart_policy:
        delay: 30s
        max_attempts: 10
        window: 120s
    networks:
      - datastream_network
  kafka2:
    image: jqrdan/datastream-kafka:1.0.0
    ports:
      - "9093:9093"
      - "8778:8778"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_LISTENERS: PLAINTEXT://:9093
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_JOLOKIA_PORT: 8778
    depends_on:
      - zookeeper
    volumes:
      - kafka02:/var/lib/kafka/data
    deploy:
      restart_policy:
        delay: 30s
        max_attempts: 10
        window: 120s
    networks:
      - datastream_network
  kafka3:
    image: jqrdan/datastream-kafka:1.0.0
    ports:
      - "9094:9094"
      - "8779:8778"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_LISTENERS: PLAINTEXT://:9094
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_JOLOKIA_PORT: 8778
    depends_on:
      - zookeeper
    volumes:
      - kafka03:/var/lib/kafka/data
    deploy:
      restart_policy:
        delay: 30s
        max_attempts: 10
        window: 120s
    networks:
      - datastream_network
  kafkarest:
    image:  confluentinc/cp-kafka-rest:5.4.0
    ports: 
      - "8082:8082"
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_LISTENERS: http://kafkarest:8082
      KAFKA_REST_HOST_NAME: kafkarest
    networks:
      - datastream_network
  topicshook:
    image: jqrdan/datastream-hooks-topics:1.0.0
    depends_on: 
      - kafka1
      - kafka2
      - kafka3
    networks:
      - datastream_network
  connectorhook:
    image: jqrdan/datastream-hooks-connectors:1.0.0
    depends_on: 
      - topicshook
    networks:
      - datastream_network
  kafkaconnect:
    image: jqrdan/datastream-connect:1.0.0
    ports:
      - "8083:8083"
    depends_on: 
      - topicshook
    networks:
      - datastream_network
  details:
    image: jqrdan/datastream-stream-details:1.0.0
    depends_on: 
      - topicshook
    networks:
      - datastream_network
  genres:
    image: jqrdan/datastream-stream-genres:1.0.0
    depends_on: 
      - topicshook
    networks:
      - datastream_network
  songs:
    image: jqrdan/datastream-stream-songs:1.0.0
    depends_on: 
      - topicshook
    networks:
      - datastream_network
  artists:
    image: jqrdan/datastream-stream-artists:1.0.0
    depends_on: 
      - topicshook
    networks:
      - datastream_network
  albums:
    image: jqrdan/datastream-stream-albums:1.0.0
    depends_on: 
      - topicshook
    networks:
      - datastream_network
  metrics:
    image: jqrdan/datastream-metrics:1.0.0
    depends_on: 
      - kafka1
      - kafka2
      - kafka3
      - es01
      - es02
      - es03
    networks:
      - datastream_network
    
volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
  kafka01:
    driver: local
  kafka02:
    driver: local
  kafka03:
    driver: local

networks:
  datastream_network:
    driver: overlay