version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    extra_hosts:
      - "es01:$(ES01)"
      - "es02:$(ES02)"
      - "es03:$(ES03)"

networks:
  default:
    external:
      name: datastream-network