version: '3.7'
services:
  details:
    image: datastream-stream-details:1.0.0
    extra_hosts:
      - "kafka1:${KAFKA}"
      - "kafka2:${KAFKA}"
      - "kafka3:${KAFKA}"
  genres:
    image: datastream-stream-genres:1.0.0
    extra_hosts:
      - "kafka1:${KAFKA}"
      - "kafka2:${KAFKA}"
      - "kafka3:${KAFKA}"
  songs:
    image: datastream-stream-songs:1.0.0
    extra_hosts:
      - "kafka1:${KAFKA}"
      - "kafka2:${KAFKA}"
      - "kafka3:${KAFKA}"

networks:
  default:
    external:
      name: datastream-network